[twitch] Strip title to avoid download error #24575
Since we create filename from title, it's very easy to get following
error:

  ERROR: unable to open for writing: [Errno 36] File name too long: ...

This commit strips title to 210 bytes so we'll fit into FS's 255 bytes
filesize limit.